/* imports.c -- GENERATED by runtime/tools/gen_imports.py; do not edit.
 *
 * Every import of liblabyrinthii that no loaded module
 * exports (gl* aside: the GL layer serves those), mapped to the host
 * function or object that serves it: b_* shims for the bionic ABI
 * (bionic_*.c, android_ndk.c, gl_*.c, the port's files), and newlib
 * directly where the two ABIs agree. Declared through asm labels so no
 * C prototype is needed (or can conflict): only the address is taken
 * here. The search over the table is the runtime's imports_lookup.c.
 *
 * Weak imports bound to NULL on purpose: __cxa_begin_cleanup, __cxa_call_unexpected, __cxa_type_match.
 * MIT.
 */
#include "imports.h"

extern const char sym_acosf[] __asm__("acosf");
extern const char sym_atan2f[] __asm__("atan2f");
extern const char sym_atanf[] __asm__("atanf");
extern const char sym_atoi[] __asm__("atoi");
extern const char sym_b__ZdaPv[] __asm__("b__ZdaPv");
extern const char sym_b__ZdlPv[] __asm__("b__ZdlPv");
extern const char sym_b__Znaj[] __asm__("b__Znaj");
extern const char sym_b__Znwj[] __asm__("b__Znwj");
extern const char sym_b___android_log_print[] __asm__("b___android_log_print");
extern const char sym_b___cxa_atexit[] __asm__("b___cxa_atexit");
extern const char sym_b___cxa_finalize[] __asm__("b___cxa_finalize");
extern const char sym_b___cxa_guard_acquire[] __asm__("b___cxa_guard_acquire");
extern const char sym_b___cxa_guard_release[] __asm__("b___cxa_guard_release");
extern const char sym_b___cxa_pure_virtual[] __asm__("b___cxa_pure_virtual");
extern const char sym_b___gnu_Unwind_Find_exidx[] __asm__("b___gnu_Unwind_Find_exidx");
extern const char sym_b___sF[] __asm__("b___sF");
extern const char sym_b___stack_chk_fail[] __asm__("b___stack_chk_fail");
extern const char sym_b___stack_chk_guard[] __asm__("b___stack_chk_guard");
extern const char sym_b__ctype_[] __asm__("b__ctype_");
extern const char sym_b__tolower_tab_[] __asm__("b__tolower_tab_");
extern const char sym_b_abort[] __asm__("b_abort");
extern const char sym_b_ceil[] __asm__("b_ceil");
extern const char sym_b_crc32[] __asm__("b_crc32");
extern const char sym_b_deflate[] __asm__("b_deflate");
extern const char sym_b_deflateEnd[] __asm__("b_deflateEnd");
extern const char sym_b_deflateInit2_[] __asm__("b_deflateInit2_");
extern const char sym_b_fclose[] __asm__("b_fclose");
extern const char sym_b_fopen[] __asm__("b_fopen");
extern const char sym_b_fprintf[] __asm__("b_fprintf");
extern const char sym_b_fputc[] __asm__("b_fputc");
extern const char sym_b_fputs[] __asm__("b_fputs");
extern const char sym_b_fread[] __asm__("b_fread");
extern const char sym_b_fseek[] __asm__("b_fseek");
extern const char sym_b_ftell[] __asm__("b_ftell");
extern const char sym_b_fwrite[] __asm__("b_fwrite");
extern const char sym_b_get_crc_table[] __asm__("b_get_crc_table");
extern const char sym_b_gettimeofday[] __asm__("b_gettimeofday");
extern const char sym_b_inflate[] __asm__("b_inflate");
extern const char sym_b_inflateEnd[] __asm__("b_inflateEnd");
extern const char sym_b_inflateInit2_[] __asm__("b_inflateInit2_");
extern const char sym_b_inflateInit_[] __asm__("b_inflateInit_");
extern const char sym_b_inflateReset[] __asm__("b_inflateReset");
extern const char sym_b_longjmp[] __asm__("b_longjmp");
extern const char sym_b_memcpy[] __asm__("b_memcpy");
extern const char sym_b_memmove[] __asm__("b_memmove");
extern const char sym_b_memset[] __asm__("b_memset");
extern const char sym_b_mkdir[] __asm__("b_mkdir");
extern const char sym_b_printf[] __asm__("b_printf");
extern const char sym_b_puts[] __asm__("b_puts");
extern const char sym_b_raise[] __asm__("b_raise");
extern const char sym_b_remove[] __asm__("b_remove");
extern const char sym_b_rename[] __asm__("b_rename");
extern const char sym_b_round[] __asm__("b_round");
extern const char sym_b_setjmp[] __asm__("b_setjmp");
extern const char sym_b_snprintf[] __asm__("b_snprintf");
extern const char sym_b_sprintf[] __asm__("b_sprintf");
extern const char sym_b_sqrtf[] __asm__("b_sqrtf");
extern const char sym_b_time[] __asm__("b_time");
extern const char sym_b_usleep[] __asm__("b_usleep");
extern const char sym_cos[] __asm__("cos");
extern const char sym_cosf[] __asm__("cosf");
extern const char sym_fmod[] __asm__("fmod");
extern const char sym_free[] __asm__("free");
extern const char sym_lrand48[] __asm__("lrand48");
extern const char sym_malloc[] __asm__("malloc");
extern const char sym_memcmp[] __asm__("memcmp");
extern const char sym_pow[] __asm__("pow");
extern const char sym_powf[] __asm__("powf");
extern const char sym_sin[] __asm__("sin");
extern const char sym_sinf[] __asm__("sinf");
extern const char sym_srand48[] __asm__("srand48");
extern const char sym_sscanf[] __asm__("sscanf");
extern const char sym_strcasecmp[] __asm__("strcasecmp");
extern const char sym_strcat[] __asm__("strcat");
extern const char sym_strchr[] __asm__("strchr");
extern const char sym_strcmp[] __asm__("strcmp");
extern const char sym_strcpy[] __asm__("strcpy");
extern const char sym_strdup[] __asm__("strdup");
extern const char sym_strlen[] __asm__("strlen");
extern const char sym_strncmp[] __asm__("strncmp");
extern const char sym_strncpy[] __asm__("strncpy");
extern const char sym_strstr[] __asm__("strstr");
extern const char sym_strtod[] __asm__("strtod");
extern const char sym_strtol[] __asm__("strtol");
extern const char sym_strtoul[] __asm__("strtoul");
extern const char sym_tanf[] __asm__("tanf");

DynLibFunction dcr_imports[] = {
    {"_ZdaPv", (uintptr_t)sym_b__ZdaPv},
    {"_ZdlPv", (uintptr_t)sym_b__ZdlPv},
    {"_Znaj", (uintptr_t)sym_b__Znaj},
    {"_Znwj", (uintptr_t)sym_b__Znwj},
    {"__android_log_print", (uintptr_t)sym_b___android_log_print},
    {"__cxa_atexit", (uintptr_t)sym_b___cxa_atexit},
    {"__cxa_finalize", (uintptr_t)sym_b___cxa_finalize},
    {"__cxa_guard_acquire", (uintptr_t)sym_b___cxa_guard_acquire},
    {"__cxa_guard_release", (uintptr_t)sym_b___cxa_guard_release},
    {"__cxa_pure_virtual", (uintptr_t)sym_b___cxa_pure_virtual},
    {"__gnu_Unwind_Find_exidx", (uintptr_t)sym_b___gnu_Unwind_Find_exidx},
    {"__sF", (uintptr_t)sym_b___sF},
    {"__stack_chk_fail", (uintptr_t)sym_b___stack_chk_fail},
    {"__stack_chk_guard", (uintptr_t)sym_b___stack_chk_guard},
    {"_ctype_", (uintptr_t)sym_b__ctype_},
    {"_tolower_tab_", (uintptr_t)sym_b__tolower_tab_},
    {"abort", (uintptr_t)sym_b_abort},
    {"acosf", (uintptr_t)sym_acosf},
    {"atan2f", (uintptr_t)sym_atan2f},
    {"atanf", (uintptr_t)sym_atanf},
    {"atoi", (uintptr_t)sym_atoi},
    {"ceil", (uintptr_t)sym_b_ceil},
    {"cos", (uintptr_t)sym_cos},
    {"cosf", (uintptr_t)sym_cosf},
    {"crc32", (uintptr_t)sym_b_crc32},
    {"deflate", (uintptr_t)sym_b_deflate},
    {"deflateEnd", (uintptr_t)sym_b_deflateEnd},
    {"deflateInit2_", (uintptr_t)sym_b_deflateInit2_},
    {"fclose", (uintptr_t)sym_b_fclose},
    {"fmod", (uintptr_t)sym_fmod},
    {"fopen", (uintptr_t)sym_b_fopen},
    {"fprintf", (uintptr_t)sym_b_fprintf},
    {"fputc", (uintptr_t)sym_b_fputc},
    {"fputs", (uintptr_t)sym_b_fputs},
    {"fread", (uintptr_t)sym_b_fread},
    {"free", (uintptr_t)sym_free},
    {"fseek", (uintptr_t)sym_b_fseek},
    {"ftell", (uintptr_t)sym_b_ftell},
    {"fwrite", (uintptr_t)sym_b_fwrite},
    {"get_crc_table", (uintptr_t)sym_b_get_crc_table},
    {"gettimeofday", (uintptr_t)sym_b_gettimeofday},
    {"inflate", (uintptr_t)sym_b_inflate},
    {"inflateEnd", (uintptr_t)sym_b_inflateEnd},
    {"inflateInit2_", (uintptr_t)sym_b_inflateInit2_},
    {"inflateInit_", (uintptr_t)sym_b_inflateInit_},
    {"inflateReset", (uintptr_t)sym_b_inflateReset},
    {"longjmp", (uintptr_t)sym_b_longjmp},
    {"lrand48", (uintptr_t)sym_lrand48},
    {"malloc", (uintptr_t)sym_malloc},
    {"memcmp", (uintptr_t)sym_memcmp},
    {"memcpy", (uintptr_t)sym_b_memcpy},
    {"memmove", (uintptr_t)sym_b_memmove},
    {"memset", (uintptr_t)sym_b_memset},
    {"mkdir", (uintptr_t)sym_b_mkdir},
    {"pow", (uintptr_t)sym_pow},
    {"powf", (uintptr_t)sym_powf},
    {"printf", (uintptr_t)sym_b_printf},
    {"puts", (uintptr_t)sym_b_puts},
    {"raise", (uintptr_t)sym_b_raise},
    {"remove", (uintptr_t)sym_b_remove},
    {"rename", (uintptr_t)sym_b_rename},
    {"round", (uintptr_t)sym_b_round},
    {"setjmp", (uintptr_t)sym_b_setjmp},
    {"sin", (uintptr_t)sym_sin},
    {"sinf", (uintptr_t)sym_sinf},
    {"snprintf", (uintptr_t)sym_b_snprintf},
    {"sprintf", (uintptr_t)sym_b_sprintf},
    {"sqrtf", (uintptr_t)sym_b_sqrtf},
    {"srand48", (uintptr_t)sym_srand48},
    {"sscanf", (uintptr_t)sym_sscanf},
    {"strcasecmp", (uintptr_t)sym_strcasecmp},
    {"strcat", (uintptr_t)sym_strcat},
    {"strchr", (uintptr_t)sym_strchr},
    {"strcmp", (uintptr_t)sym_strcmp},
    {"strcpy", (uintptr_t)sym_strcpy},
    {"strdup", (uintptr_t)sym_strdup},
    {"strlen", (uintptr_t)sym_strlen},
    {"strncmp", (uintptr_t)sym_strncmp},
    {"strncpy", (uintptr_t)sym_strncpy},
    {"strstr", (uintptr_t)sym_strstr},
    {"strtod", (uintptr_t)sym_strtod},
    {"strtol", (uintptr_t)sym_strtol},
    {"strtoul", (uintptr_t)sym_strtoul},
    {"tanf", (uintptr_t)sym_tanf},
    {"time", (uintptr_t)sym_b_time},
    {"usleep", (uintptr_t)sym_b_usleep},
    {"", 0},
};

int dcr_imports_count = (int)(sizeof(dcr_imports) / sizeof(dcr_imports[0])) - 1;
